README.md
Here's the original asset fwiw:
=> Add the new logo to the readme

chrome-launcher.ts
A small change from https://github.com/GoogleChrome/lighthouse/pull/2616/files I liked
=> log pid to kill

chrome-finder.ts
In order to address https://github.com/GoogleChrome/lighthouse/issues/3270
=> only include PROGRAMFILES(X86) if present

chrome-finder.ts, chrome-launcher.ts, package.json, test/utils-test.ts, utils.ts, yarn.lock
=> Add support for WSL platform

chrome-finder.ts
Fixes https://github.com/GoogleChrome/lighthouse/issues/2652
=> Avoid selecting google-emacs

README.md
=> docs: update maxConnectionRetries default to 50

chrome-finder.ts, utils.ts
https://github.com/GoogleChrome/chrome-launcher/pull/51
Fixes #46 
Closes #51
=> Address comments from from PR 51

README.md
=> readme: recommend use of cri with chrome-launcher

src/chrome-finder.ts, src/utils.ts, test/utils-test.ts
=> Fix getLocalAppDataPath for wsl

package.json, src/chrome-finder.ts, src/chrome-launcher.ts, src/utils.ts, yarn.lock
=> Fixes typescript typing issues

package.json, src/chrome-finder.ts, src/chrome-launcher.ts, src/utils.ts, yarn.lock
This PR introduces error codes ([further reading](https://medium.com/the-node-js-collection/node-js-errors-changes-you-need-to-know-about-dc8c82417f65)).
**Why?**
It is easier to catch specific errors with something like —
```
try {
...
} catch (err) {
if (err.code === 'ERR_CHROME_PATH_NOT_SET') {}
}
```
instead of —
```
try {
...
} catch (err) {
if (err.message.startsWith(`The environment variable CHROME_PATH`)) {}
}
```
=> Set custom error codes for all errors

src/chrome-finder.ts
=> Fix picking CHROME_PATH priority over other matches

README.md
Fix readme typo: booelan ==> boolean
=> Fix readme typo: booelan ==> boolean

src/chrome-launcher.ts
Reduce possible set of input values to the allowed input values.
=> Stricter typing for logLevel

.travis.yml, manual-chrome-launcher.js, package.json
this woulda failed the #70 had it been in
=> typecheck the JS files to confirm the typed API

docs/chrome-flags-for-tools.md
=> fix link to chrome-launcher's flags

src/chrome-finder.ts
Fixes #100. This is just @paulirish's PR (#129), but with an extra commit to fix formatting so that it passes CI.
=> silence grep

src/flags.ts
See https://chromium.googlesource.com/chromium/src.git/+/ba49d00fddeb39c0816090dad7d359df0dce9a1a
=> Removing a dead flag.

README.md, manual-chrome-launcher.js, src/chrome-launcher.ts, test/chrome-launcher-test.ts
Originally written in #70. Landed and then later reverted in #120 as its a breaking change that necessitates a major release.
(This PR won't be passing due to the typechecking and correct export of defaultFlags)
=> remove enableExtensions option. add ignoreDefaultFlags option, add defaultFlags() method

package.json, yarn.lock
to fix the critical security alert:
=> deps(security): bump mocha to latest

src/chrome-launcher.ts
=> fix: log taskkill error based on logging opts (#178)

package.json, test/chrome-launcher-test.ts, yarn.lock
Fixes a vulnerability:
https://snyk.io/test/npm/chrome-launcher/0.13.0
> Introduced through: chrome-launcher@0.13.0 › mkdirp@0.5.1 › minimist@0.0.8
=> deps: update various dependencies

README.md
Fixes #168
- DefaultFlags function documented correctly
=> Fixes #168

docs/chrome-flags-for-tools.md, src/flags.ts
big massive update to `docs/chrome-flags-for-tools.md`
added a bunch of new ones, added descriptions. added new `removed` items.
categorized and sorted.
=> docs(chrome-flags-for-tools): massive update and refactor

docs/chrome-flags-for-tools.md
Updated chrome-flags-for-tools.md with flags to replace camera.
=> docs: Update chrome-flags-for-tools.md

src/chrome-launcher.ts
=> fix chrome connection in node 17, use 127.0.0.1 explicitly

.github/workflows/ci.yml
we have pretty extensive tests over in the Lighthouse repo on Node 16 and 17, but need to update occasionally :)
=> test: run latest versions of node in CI

src/chrome-launcher.ts
ref https://github.com/GoogleChrome/lighthouse/issues/14769#issuecomment-1423420623
=> log when connection to existing chrome found for requested port

src/chrome-launcher.ts
to match https://github.com/GoogleChrome/lighthouse/pull/14964
=> Update logLevel option typing

README.md
Closes https://github.com/GoogleChrome/chrome-launcher/issues/312
=> Update readme for 1.0.0

src/chrome-launcher.ts, test/chrome-launcher-test.ts
reference:
- [https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/test/chromedriver/chrome_launcher.cc](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/test/chromedriver/chrome_launcher.cc), method: PrepareUserDataDir
- [https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/common/chrome_constants.cc](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/common/chrome_constants.cc), constants: kInitialProfile, kPreferencesFilename
=> fix: set browser preferences correctly

.github/workflows/lh-smoke.yml
This matches what we have in LH's own CI:
https://github.com/GoogleChrome/lighthouse/blob/7d2e59fc6900823d1d46d22434ee571f351967b7/.github/workflows/smoke.yml#L111
=> ci(smoke): allow 5 retries

docs/chrome-flags-for-tools.md, src/flags.ts
After triaging what new flags all the other tools should use I finally did some of the same.  most of these are for removing extra background networking. but a few are behavior changes that will improve reliability.
cc @benschwarz since you were lookin at this recently
=> flags: add additional flags
