- .appveyor.yml
- README.md
- scripts/download-chrome.sh
also bring over download-chrome.sh from lh-core
see https://ci.appveyor.com/project/paulirish/chrome-launcher/history
> Add Appveyor CI

- README.md
- chrome-launcher.ts
This PR is a copy of https://github.com/GoogleChrome/lighthouse/pull/3129 and addresses #12 
Also this may fix https://github.com/GoogleChrome/lighthouse/pull/2616, because the main goal is to avoid `ECONNREFUSED`. In my experiments, this issue was related with not enough time in 100% cases, just increase from 5s to 25s fixed `ECONNREFUSED`.
> add support for `connectionPollInterval ` and `maxConnectionRetries`

- chrome-launcher.ts
As noted in #19, some have found success just waiting longer for the port to connect.
This will now poll every 500ms (unchanged) for a maximum of 25 seconds. (previously 5s).
Fixes #6, https://github.com/GoogleChrome/lighthouse/issues/2556
Invalidates https://github.com/GoogleChrome/lighthouse/pull/2616
> Retry connection for longer

- README.md
The URL of chromeFlags references lighthouse repository.
So I will fix it to point to the URL of the chrome-launcher.
> docs: fix the url of chromeFlags in the README

- README.md
- chrome-launcher.ts
- test/chrome-launcher-test.ts
Add a new property `defaultProfile` to use the default user's profile in Chrome instead of creating a new one. By default this value is `false` so it doesn't change the current behavior.
Close #47
> New: Add flag to use default user profile instead

- .gitignore
Without this node_modules shows up in the working .git tree
making it hard to reason about what you have changed and what should be
checked in.
Since we are not vendoring node_modules there is no reason we can not
ignore node_modules from git via .gitignore.
> Ignore node_modules from git.

- chrome-launcher.ts
This will make it so users can do
```js
import chromeLauncher from 'chrome-launcher';
```
This in some cases provides a nicer end user DX, and since it still
retains the old behavior of also exporting a named export this is not a
breaking change. For this reason I postulate that this is an overall win
to consumers of the API.
Fixes #37
> Make launcher the default export.

- README.md
- chrome-launcher.ts
- test/chrome-launcher-test.ts
Since it can be useful for users to programatically set env vars
for a given instance of chrome, expose the ability for users to pass
in a env dict into the spawn command that is used to launch chrome.
FIXES #29
---
Sidebar I will refactor the tests to DRY up existing implementations with a follow on CL. I chose to omit it from this CL as it increases the scope of the changeset and muddies the intent of this change.
> Enable users to pass env vars into spawned chrome.

- README.md
- chrome-launcher.ts
- test/launch-signature-test.ts
Some users may want/need access to the underlying child process as
generated from the spawn command, so expose it when launching chrome.
Also add a test to make sure that the interface that we return does not
have undefined values set.
---
This PR is from #40 but cleaned up so that we can land it.
fixes #7
> Expose launched chrome child process object.

- src/chrome-launcher.ts
if you've tried to launch canary today you may have noticed some strange behavior...
even if you ctrl-c, it just keeps on chugging. turns out we never resolve/reject the promise on a failed kill and so our sig int handler sits there forever
> fix: reject promise on failed kill

- src/chrome-finder.ts
Add `{ stdio: 'ignore' }` to execFileSync to make sure no output is generated to our output buffers.
fixes https://github.com/GoogleChrome/lighthouse/issues/5795
> fix(output): ignore stdio channels (stdout, stdin, stderr)

- README.md
- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
It's breaking and we need to ship a patch release.
Also we need typechecking enabled on JS as #70 didn't correctly export `defaultFlags`.
> Revert defaultFlags change 

- src/chrome-finder.ts
looks like I broke something when setting the stdio to ignore. When setting it to pipe we output everything to it's parent process even stderr.
I tested it on docker and it works. The function doesn't return any stderr commands but it does return the chrome paths with which. `stdio: ignore` actually broke in docker too but we could manage to fetch the chrome executable from `/usr/share/applications/` or `~/.local/share/applications/`.
> fix: set stdio to pipe

- package.json
- src/chrome-launcher.ts
- src/random-port.ts
> fix: move unneeded ts types to devDeps

- .appveyor.yml
- .travis.yml
- package.json
Add support of WSL 2 by updating `is-wsl` to version `2.1.0`, which in fact does not support Node 6.
This request:
- updates `is-wsl` dependency 
- drops Node 6 support
- adds Node 10/12 support
> Add WSL 2 support and remove Node 6 support

- src/chrome-finder.ts
Mac OS Catalina appends a hex code to the end of the path output by LSRegisters, the regex that finds all the chrome executables looked for a newline immediately following the end of the .app. 
Now the regex finds the paths again, and hex code is trimmed off before being tested for file access and added to the array
Fixes #146
> Fix MacOS Catalina Regex issue

- docs/chrome-flags-for-tools.md
Was having trouble with Chrome not automatically retrying requests until I realized that `--enable-automation` breaks that behavior, which should be documented here.
> Document that --enable-automation disables automatic page reloads

- .travis.yml
as mentioned here https://github.com/GoogleChrome/chrome-launcher/pull/158#pullrequestreview-259793476
> tests: drop support for node 9. continue supporting node 8 LTS

- README.md
The example was referencing a value that wasn't defined ✌️
> Fix launcher example in README

- src/chrome-launcher.ts
- src/flags.ts
- test/chrome-launcher-test.ts
The default Chrome flags were being mutated by the `flags` method. This led to changes in the default flags over time, which presumably was not intended.
The default flags are now shallowly cloned to prevent mutation. The TypeScript type has been set to `ReadonlyArray` to prevent this from happening in the future.
> fix: Prevent mutation of default flags

- src/flags.ts
In this PR: 
---
I noticed that Lighthouse currently displays the translation UI despite chrome-launcher using the `--disable-translation` flag. 
The `--disable-translation` flag is no longer listed on [Peter Beverloo's command line switches page](https://peter.sh/experiments/chromium-command-line-switches/). 
It seems that to achieve the same result, the `--disable-features=TranslateUI` flag must be used. 
closes https://github.com/GoogleChrome/chrome-launcher/issues/88
> Update the translation flag

- .travis.yml
- package.json
- yarn.lock
makes github UI warnings go away (all in transitive devDependencies)
Slightly more than usual, though: two of the bad dependencies were deep in `nyc`'s transitive deps and didn't trivially update to non-vulnerable versions. Rather than update the version of nyc, make sure everything is working as before, etc, I just removed nyc :)
I don't think I've ever used coverage on `chrome-launcher` since it split from the `lighthouse` repo and we don't upload the coverage reports anywhere...any reason to keep?
> deps: update assorted dependencies

- README.md
- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
Add `Launcher.getInstallations()` public static method that returns an
array of paths to available Chrome binaries. Also, refactor
`Launcher#launch()` to use it.
`Launcher.getInstallations()` uses `chrome-finder` under the hood, so all
previous resolution logic is preserved:
- if `CHROME_PATH` env variable is set, it will be included
- if a Chrome Canary is detected, it will be included
- if a Chrome (stable) is detected, it will be included
Resolves #176
> feat: expose public interface for locating Chrome installations

- docs/chrome-flags-for-tools.md
- src/flags.ts
described mostly here: https://blog.bigbinary.com/2018/08/15/debugging-failing-tests-in-background-tab-in-puppeteer.html
also relevant: https://github.com/GoogleChrome/puppeteer/blame/master/lib/Launcher.js
test page for occlusion and timer drift: https://output.jsbin.com/goduxox/1/quiet
ref #169
> flags: add new --disable flags to reduce noise and disable backgrounding

- README.md
npmjs.com formatted code strange due to missing closing quote.
> docs: added missing quote in README.md example

- docs/chrome-flags-for-tools.md
- src/flags.ts
It appears that the `--no-default-browser-check` flag is still there and still functioning.
https://github.com/chromium/chromium/blob/cbbe680/chrome/browser/ui/startup/startup_browser_creator_impl.cc#L870-L876
closes #181
> flags: disable the default browser check (#181)

- package.json
- src/chrome-finder.ts
The `PATH` and `CHROME_PATH` variables are currently being used verbatim for constructing a regular expression:
https://github.com/GoogleChrome/chrome-launcher/blob/9aa64d642d3af13e447f8f84cacb05e556ff036e/src/chrome-finder.ts#L52-L53
This can lead to confusing behaviour if a user's path contains RegExp metacharacters such as `$` or `^`. Worse still, it leaves room for a malicious actor to inject an expression guaranteed to send the process into performance hell:
~~~shell
export CHROME_PATH='(.*.*.*.*.*.*.*.*.*.*.*.*)*[^Bb]|$'
~~~
I also replaced stuff like `` `${process.env.PATH}` `` with simply `process.env.PATH`, because the former syntax will stringify an undefined value as `"undefined"`, which probably isn't what you want (or expect).
> Sanitise environment variables used in RegExps

- package.json
- yarn.lock
edit: ignore everything after the hr
just bringing over two small fixes. one for linux and one for docker. https://github.com/sindresorhus/is-wsl/releases
------------
wsl2 happened and is-wsl added support: https://github.com/sindresorhus/is-wsl/pull/3
ref https://github.com/GoogleChrome/lighthouse/issues/10288
> deps: bump to is-wsl@2.2.0 

- test/chrome-launcher-test.ts
- test/launch-signature-test.ts
The non-strict versions are deprecated. I've not changed the usage of `equal` in `utils-test` as the tests are replaced in #200 (which already uses the strict versions), and so would just cause a merge conflict.
> test: use strict version of assert functions

- package.json
- test/launch-signature-test.ts
- yarn.lock
Latest TypeScript is more accurate, faster, and mathematically higher 🥳
I also updated `@types/rimraf`, and `@types/sinon`: while this is bumping majors, it's raising them to match the current version of the package in use, as `@types` packages match the major.minor version of the package their typing (i.e so `@types/sinon@9` should be used for `sinon@9`, while `@types/sinon@7` should be used for `sinon@7`)
This revealed that the `this.timeout =` assignment being done in a test was invalid (since arrow functions don't have access to the mocha context); it's actually not needed because the timeout is set higher than 3500 via the launching flag.
> Update typescript & types

- src/flags.ts
see 🔒  crbug.com/1058632 for details
it appears this affects canary/dev much more than stable. 
In Lighthouse we normally don't see this error in CLI cases where we have a fresh profile, but rather in devtools. But regardless, it makes sense to avoid background tracing regardless.
fixes (partially) https://github.com/GoogleChrome/lighthouse/issues/1091
> flags: disable background tracing

- README.md
`getInstallations()` is a method  of `Launcher` class
> Fix getInstallations() section

- .appveyor.yml
- .travis.yml
- README.md
- package.json
- src/chrome-finder.ts
- src/chrome-launcher.ts
- src/utils.ts
- test/chrome-launcher-test.ts
- test/random-port-test.ts
- test/utils-test.ts
- yarn.lock
* Update TypeScript and other dependencies.
* Update test targets. Current `LTS` and `stable` are `14.x` and `15.x` (https://nodejs.org/en/about/releases/).
* Cleanup code; update imports to improve type hints and remove deprecations.
> Update dependencies and test targets

- src/flags.ts
TranslateUI isn't a thing as of several months ago (https://chromium-review.googlesource.com/c/chromium/src/+/2404484). There are probably more stale ones we should look into, but didn't want to forget this one.
> fix: rename TranslateUI to Translate to match Chrome

- .appveyor.yml
- .travis.yml
- package.json
- yarn.lock
Drop support for Node.js 8, which is no longer supported: https://nodejs.org/en/about/releases/
> Require Node.js 10+

- .github/workflows/ci.yml
- test/chrome-launcher-test.ts
only linux.
once landed, we can drop travis. 
we can also add windows and drop appveyor. and maybe add mac.
> tests(ci): migrate from travis to github actions

- docs/chrome-flags-for-tools.md
- src/flags.ts
extra descriptions of these at https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md
- `disable-component-update`.. this is huge, as I don't believe `disable-background-networking` was toggling this off.
- `disable-client-side-phishing-detection`. probably not a huge deal, but why not.
- `disable-ipc-flooding-protection`. Been default in pptr since 2018. https://github.com/puppeteer/puppeteer/commit/2a88690582cf01c8a338a972b352c34738e6bfdf seems good
- `password-store=basic` and `use-mock-keychain`. default in chromedriver/pptr.  see links in the markdown.
- `enable-automation`. most of the [benefits](https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#test--debugging-flags) are great, but the added infobar caused …
> Add additional chrome flags

- package.json
- src/utils.ts
- yarn.lock
Node.js 10 LTS has recursive `fs.mkdirSync` so that we don't need mkdirp package.
https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_mkdirsync_path_options
I tested on Windows 10 64bit 20H2 since mkdirp is used only on Windows.
> deps: replace mkdirp.sync with fs.mkdirSync

- .github/workflows/ci.yml
- README.md
- package.json
- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
- tsconfig.json
- yarn.lock
Node 10 will be EoL on April 30, just about the time we might possibly do another release of chrome-launcher, so seems ok to do now.
We should bump the next release to `0.14.0`, though.
With node 12 comes `fs.rmdir(path, {recursive: true})`, so we don't need rimraf anymore.
> move to minimum node 12; remove rimraf

- test/chrome-launcher-test.ts
trying to fix failed CI on the mac (e.g. https://github.com/GoogleChrome/chrome-launcher/runs/2348391043), assuming this is a really slow `execSync` thing.
> tests(mac): longer timeout for finding installations

- README.md
- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
implements: #213
In [WebdriverIO](https://webdriver.io/) we offer to run automated browser tests using WebDriver or CDP (via Puppeteer). When we start a Puppeteer browser we use this package as it gives us more options to set the browser session. However it is not possible to set a custom set of browser preferences, e.g. to define the default download directory. This patch adds this capability to the package. To create feature parity given that Chromedriver allows this, it would be great if we could add this.
> feat: Allow user to set browser preferences

- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
In node v14.14+ a deprecation warning is now always given:
[DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
nodejs.org/api/deprecations.html#DEP0147
So I've checked for the existence of `fs.rm` in favor of `fs.rmdir` if available, which should support v16+ but also v12.
> fix: forwards support for fs.rm in node 14.14+

- bin/print-chrome-path.js
- package.json
- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
Using Lighthouse user flows, I find myself alternating between being fine with the version of Chrome shipped with puppeteer and needing the Canary installed on my machine, depending on what I'm doing, but it's awkward to set the path manually, and it's not portable (e.g. for sample code)
`chrome-launcher` is already set up to find Canary, so I've been wanting a way to be able to easily run something like
```js
const browser = await puppeteer.launch({
headless: false,
executablePath: chromeLauncher.getChromePath(),
});
```
I don't see any non-ugly way of reaching into `chrome-launcher` to do this (someone correct me if I'm wrong), so this PR exposes a function to do this.
Also adds a bin option as I've also wanted it on the command line, e.g. `CHROME_PATH="$(npm exec print-chrome-path)"`. …
> add method for printing found chrome path

- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
per #266 there's no reason for this to be async.  keeping it async adds extra challenges to both debugging and understanding the flow.
also, added a function test for userdatadir removal
for review, turn off whitespace
> make launcher.kill() synchronous

- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
- test/launch-signature-test.ts
@paulirish https://github.com/GoogleChrome/chrome-launcher/pull/268#issuecomment-1151335466
> Make LaunchedChrome.kill sync

- .github/workflows/ci.yml
- .github/workflows/lh-smoke.yml
- README.md
- docs/chrome-flags-for-tools.md
- src/flags.ts
I already made the branch name change here, as of 5 minutes ago. If you have a local git checkout of this repo... run the following before your next pull:
```sh
git branch -m master main; git fetch origin; git branch -u origin/main main; git remote set-head origin -a
```
---------------------
of the changes:
* 1 of these is LH repo
* a few are the chrome-launcher repo
* and then a few are chromium repo
> rename master branch references to main

- docs/chrome-flags-for-tools.md
- src/flags.ts
.. and update the flags.md some more.
With `--enable-logging=stderr --v=2` you'll see both optimization guide and media router (aka cast_transform) pretty actively making network requests. 
--------
I also made this spreadsheet to make it easier to compare who uses what. https://docs.google.com/spreadsheets/d/1n-vw_PCPS45jX3Jt9jQaAhFqBY6Ge1vWF_Pa0k7dCk4/edit#gid=1265672696 (As I end up manually doing it about once a year)
> flags: disable optimization guide and media router

- .github/workflows/ci.yml
- .github/workflows/lh-smoke.yml
..... 
okay it it looks happy now :)
> use updating node versions in CI

- docs/chrome-flags-for-tools.md
As of https://bugs.chromium.org/p/chromium/issues/detail?id=1380881 (corresponding CL https://chromium-review.googlesource.com/c/chromium/src/+/4000223 ), the flag for this new headless mode has been renamed.
> Update headless=chrome flag to headless=new

- src/chrome-launcher.ts
It should closeSync outFile and errFile when userDataDir is custom.
fixes #260
> fix: always close file handles to stdout/stderr logs

- docs/chrome-flags-for-tools.md
The previously linked CL seems unrelated.
> docs(flags): --disable-infobars fix link to removal CL

- docs/chrome-flags-for-tools.md
- src/flags.ts
We noticed this dialog started showing up in canary as of ~today. 
Not sure what happened but.. after speaking to an eng on that team, this'll ensure it's hidden.
There's also a profile signal they'll use, so.. as of tomorrow's canary this flag shouldn't be needed.
Regardless, good to ensure it doesn't pop up.
> flags: disable privacy sandbox dialog

- docs/chrome-flags-for-tools.md
- src/flags.ts
This disables the annoying UI help bubbles that appear when Chrome is opened "for the first time" which actually means every time for our setup.
See b/340895256 for more context.
> flags: disable in-product health system

- README.md
- src/chrome-launcher.ts
- test/chrome-launcher-test.ts
- test/chrome_extension_fixture/background.js
- test/chrome_extension_fixture/contentscript.js
- test/chrome_extension_fixture/manifest.json
- test/load-extension-test.ts
Historically, the `--load-extension` option in chromeFlags could be used to launch Chrome with an extension installed. This flag is no longer supported in official stable Chrome releases since Chrome 137. The `--remote-debugging-pipe` is the official alternative. To support this, `chrome-launcher` needs to pass two additional pipes.
This patch also includes a full test that serves as a form of documentation on how one can load an extension with `chrome-launcher`.
For more context, see https://github.com/mozilla/web-ext/issues/3388
Fixes #289
> feat: Support remote-debugging-pipe and add loadExtension test/example
